### PR TITLE
fix : msat parsing in pay view

### LINKED ISSUE #80: bug : CLNAPP send Payment error.
When sending the amount to an invoice using the CLNAPP, it throws below error : 

"NoSuchMethodError: The method '[ ]' was called on null. 
Receiver : null 
Tried calling : [ ]("msat") " 

pymnt error

### PR DESCRIPTION
**Pull request by Harshit933**
fixes the crashing of the app in pay view whenever an invoice is paid.

fix #80

### CODE REVIEW

File: lib/views/pay/pay_view.dart [hunk 1]
```diff
@@ -101,7 +101,7 @@ class _PayViewState extends State<PayView> {
           paymentResponse != null
               ? paymentResponse!.payResponse["Error"] == null
                   ? Text(
-                      "Payment Successfully : ${paymentResponse!.payResponse["amountMsat"]["msat"]} msats")
+                      "Payment Successfully done! : ${paymentResponse!.payResponse["amount_msat"]}")
```
Comment (vincenzopalazzo) [inline lib/views/pay/pay_view.dart:104]: No this do not work too.

Look how it is done this model https://github.com/dart-lightning/lndart.clnapp/blob/main/lib/model/app_model/list_funds.dart and how it is used inside the code

Comment (Harshit933) [reply lib/views/pay/pay_view.dart]: Yes, I figured that out,

**Review by vincenzopalazzo — APPROVED** [review]
OOOH NICE!

**Review by vincenzopalazzo — APPROVED** [review]

File: lib/views/pay/pay_view.dart [hunk 2]
```diff
@@ -17,18 +17,14 @@ class _PayViewState extends State<PayView> {
...
-    } catch (ex) {
-      AppPayInvoice error =
-          AppPayInvoice(payResponse: {"Error": ex.toString()});
-      return error;
-    }
+    // we don't need error handling here
+    final response = await widget.provider
+        .get<AppApi>()
+        .payInvoice(invoice: boltString, msat: amountMsat);
+    return response;
```
[the remark this answers is not in the document]
Comment (Harshit933) [reply lib/views/pay/pay_view.dart:27]: We did needed an error handling there, the pay command can return a message error. Should've fixed it earlier. My bad.

File: lib/model/app_model/pay_invoice.dart [hunk 3]
```diff
@@ -1,19 +1,64 @@
...
+    required this.status,
+    required this.amountMSAT,
+    required this.paymentHash,
+    required this.amountSentMSAT,
+  });
+
+  factory AppPay.fromJSON(Map<String, dynamic> json, {bool snackCase = false}) {
+    var destination = json.withKey("destination", snackCase: snackCase);
+    var paymentPreimage =
+        json.parseMsat(key: "payment_preimage", snackCase: true);
```
Comment (Ram-lankada) [inline lib/model/app_model/pay_invoice.dart:48]: this should be withKey right?

Comment (Harshit933) [reply lib/model/app_model/pay_invoice.dart:48]: Yes, it should be. Thank you for letting me know. I'll fix this in the follow up PR.

File: lib/views/pay/pay_view.dart (hunk 2 above)
[the remark this answers is not in the document]
Comment (vincenzopalazzo) [reply lib/views/pay/pay_view.dart:27]: we need to rework all our error handling because we do not have one? :)

Maybe we can work with from the following issue? https://github.com/dart-lightning/lndart.clnapp/issues/89

[the remark this answers is not in the document]
Comment (Harshit933) [reply lib/views/pay/pay_view.dart:27]: Sure
