### PR TITLE
fix: bump decode to package

### LINKED ISSUE #92: decodeinvoice with a library
We can use https://pub.dev/packages/bolt11_decoder to decode the bolt11, but we still need to call cln to decode a bolt12

### PR DESCRIPTION
**Pull request by Harshit933**
fix #92 

Added the package to decode the paid bolt11 invoices. 

Also added a fix to the previous paid invoices bug on android.

Attaching the screenshot for the same.

image

### CODE REVIEW

**Review by vincenzopalazzo — COMMENTED** [review]
I do not understand why we are changing the listinvoice

File: lib/model/app_model/list_invoices.dart [hunk 1]
```diff
@@ -1,8 +1,9 @@
 import 'package:cln_common/cln_common.dart';
 import 'package:clnapp/model/app_model/app_utils.dart';
+import 'package:bolt11_decoder/bolt11_decoder.dart' as pay_req;
 
 class AppListInvoices {
-  List<AppInvoice> invoice;
+  List<AppInvoice?> invoice;
```
[the remark this answers is not in the document]
Comment (Harshit933) [reply lib/model/app_model/list_invoices.dart:6]: Oh I was testing the error in list invoices I left it there. I will change it.

**Comment by Harshit933** [comment]
I think there are still some things which are needed to be taken care of. Like the prefix returns an enum. I will commit the changes in this branch only.

File: lib/model/app_model/list_invoices.dart [hunk 2]
```diff
@@ -70,7 +70,17 @@ class AppInvoice {
...
+    String prefix = '';
+    if (pre == pay_req.PayRequestPrefix.lntb) {
+      prefix = "lntb";
+    } else if (pre == pay_req.PayRequestPrefix.lnbcrt) {
+      prefix = "lncbrt";
+    } else if (pre == pay_req.PayRequestPrefix.lnbc) {
+      prefix = "lnbc";
+    } else {
+      prefix = "lnsb";
+    }
```
Comment (vincenzopalazzo) [inline lib/model/app_model/list_invoices.dart:80]: you should document what this if else is doing!

Comment (Harshit933) [reply lib/model/app_model/list_invoices.dart:80]: Oh yes yes, I will update it.

File: lib/model/app_model/list_invoices.dart [hunk 3]
```diff
@@ -9,80 +10,88 @@ class AppListInvoices {
   factory AppListInvoices.fromJSON(Map<String, dynamic> json,
       {bool snackCase = false, bool isObject = false, String? status}) {
     var invoices = json.withKey("invoices", snackCase: snackCase) as List;
+    List<AppInvoice> list = [];
+
     if (invoices.isNotEmpty) {
-      var appInvoices = invoices.map((invoice) {
-        var temp = AppInvoice.fromJSON(invoice,
+      for (int i = 0; i < invoices.length; i++) {
```
Comment (vincenzopalazzo) [inline lib/model/app_model/list_invoices.dart:16]:
```suggestion
      for (var invoice in invoices) {
```
this syntax will not work?

File: lib/model/app_model/list_invoices.dart [hunk 4]
```diff
@@ -9,80 +10,88 @@ class AppListInvoices {
...
+    /// Tells us about the prefix of the payment request whether it is of lightning invoice or other.
+    if (pre == pay_req.PayRequestPrefix.lntb) {
+      prefix = "lntb";
+    } else if (pre == pay_req.PayRequestPrefix.lnbcrt) {
+      prefix = "lncbrt";
+    } else if (pre == pay_req.PayRequestPrefix.lnbc) {
+      prefix = "lnbc";
+    } else {
+      prefix = "lnsb";
+    }
```
Comment (vincenzopalazzo) [inline lib/model/app_model/list_invoices.dart:82]: Ah ok I got it, we do not cate about the prefix inside the UI! it is uggly no?

File: lib/model/app_model/list_invoices.dart [hunk 5]
```diff
@@ -9,80 +10,88 @@ class AppListInvoices {
...
+      amount: amount.toString(),
       status: status ?? "unpaid",
-      amount: received.toString(),
-      paidTime: paidAt != null ? paidAt.toString() : "unpaid",
-      description: description,
-      label: label,
+      paymentRequest: paymentRequest,
+      prefix: prefix.toString(),
+      signature: signature,
+      tags: tags,
```
Comment (vincenzopalazzo) [inline lib/model/app_model/list_invoices.dart:93]:
```suggestion
      tags: tags,
```

The only think that I care about is knowing the description that is inside the invoice if any, we can avoid all this information without sense like the signature, or payment request.

A good think that we need to show is if the invoice was paid or not, and we need to put the bolt11 inside a QR code

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]

File: lib/model/app_model/list_invoices.dart (hunk 5 above)
Comment (Harshit933) [reply lib/model/app_model/list_invoices.dart:93]: This package does not have the description of the invoice.

File: lib/model/app_model/list_invoices.dart (hunk 4 above)
Comment (Harshit933) [reply lib/model/app_model/list_invoices.dart:82]: Yes, it is kind of ugly. I'll change it.

**Review by vincenzopalazzo — COMMENTED** [review]
I did not review it because it is not working on the demo built as preview

Selection_016

File: lib/model/app_model/list_invoices.dart [hunk 6]
```diff
@@ -9,80 +10,60 @@ class AppListInvoices {
...
-    var received = json.parseMsat(
-        key: "amountReceivedMsat", snackCase: snackCase, isObject: isObject);
-    received.toString();
-    var paidAt = json.withKey("paidAt", snackCase: snackCase);
     var description = json.withKey("description", snackCase: snackCase);
-    var label = json.withKey("label", snackCase: snackCase);
+    pay_req.Bolt11PaymentRequest req = pay_req.Bolt11PaymentRequest(bolt11);
+    LogManager.getInstance.debug(
+        "NEW RESPONSE HERE : ${req.amount} ${req.paymentRequest} ${req.prefix} ${req.signature} ${req.tags} ${req.timestamp}");
+    var amount = req.amount;
```
Comment (vincenzopalazzo) [inline lib/model/app_model/list_invoices.dart:61]: possible that this is null? from my that I post before?

**Review by vincenzopalazzo — COMMENTED** [review]
Running the app on my desktop I found the following stacktrace, maybe can help you

```
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   LogManager.debug (package:cln_common/src/logger/logger_manager.dart:16:13)
flutter: │ #1   new AppInvoice.fromJSON (package:clnapp/model/app_model/list_invoices.dart:54:28)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 {amount_msat: 1000msat, amount_received_msat: 1000msat, bolt12: lni1qss0clu47elz6kh2wj68yhv7y9qyxvz3r4faztna7nz7vne65m85mzggqgp7szsddf6hxapqw3jhxarfdennxrq9sqqqyssqrcswysy2f8c86t6qswj8x3qn3mufuashucu3jgpvj24g6jd4wjjkpt3xyqk7ts8j37wh6yxqcz67eyhg87dlgr00906qrqwq7sesc4l932rq22qyvyn4m4f2yq6k2lk49dqcw42r7xa8p6ljj77htqgtd3a0t4678la3zxjc3eljutqptgmqpuzqxepmnpfdz0md2ffrdl6dwgy585txcp7cxhlhtdhgrs8rdr7r7xmmnamyam0ll967swvngpt0ptea9f048pd73fvqt20dhegmyft9fug, description: just testing3, expires_at: 1629969967, label: @vincenzopalazzo, msatoshi: 1000, msatoshi_received: 1000, paid_at: 1629969879, pay_index: 13, payment_hash: 35657ed52b41875543f1ba70ebf297bd75810b6c7af5d75e3ffb111a588e7f2e, payment_preimage: b76fdada7c23e2a477711d1f8aa822fae7f4b054a17d9ba02a1e66efbab500ff, status: paid}
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   LogManager.error (package:cln_common/src/logger/logger_manager.dart:20:13)
flutter: │ #1   _HomeViewState._checkIfThereAreError (package:clnapp/views/home/home_view.dart:259:30)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ ⛔ type 'Null' is not a subtype of type 'String'
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   LogManager.error (package:cln_common/src/logger/logger_manager.dart:20:13)
flutter: │ #1   _HomeViewState._checkIfThereAreError (package:clnapp/views/home/home_view.dart:260:30)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ ⛔ #0      new AppInvoice.fromJSON (package:clnapp/model/app_model/list_invoices.dart:58:69)
flutter: │ ⛔ #1      new AppListInvoices.fromJSON (package:clnapp/model/app_model/list_invoices.dart:17:38)
flutter: │ ⛔ #2      CLNApi.listInvoices.<anonymous closure> (package:clnapp/api/cln/cln_client.dart:114:53)
flutter: │ ⛔ #3      LNLambdaClient.call (package:lnlambda/src/lnlambda_base.dart:26:22)
flutter: │ ⛔ <asynchronous suspension>
flutter: │ ⛔ #4      _HomeViewState.listPayments (package:clnapp/views/home/home_view.dart:117:9)
flutter: │ ⛔ <asynchronous suspension>
flutter: │ ⛔ #5      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:628:33)
flutter: │ ⛔ <asynchronous suspension>
flutter: │ ⛔ 
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Another exception was thrown: The showSnackBar() method cannot be called during build.

```

File: lib/model/app_model/list_invoices.dart (hunk 6 above)
Comment (Harshit933) [reply lib/model/app_model/list_invoices.dart:61]: I guess the bolt12 invoices are not handeled and the post you shared above has an bolt12 invoice.

Comment (vincenzopalazzo) [reply lib/model/app_model/list_invoices.dart:61]: well we should not crash, but just not decode it and spring the raw bolt12

**Comment by Harshit933** [comment]
This also produces some errors i guess

File: lib/model/app_model/list_invoices.dart [hunk 7]
```diff
@@ -31,7 +31,7 @@ class AppListInvoices {
 
 class AppInvoice {
   /// bolt11 identifier
-  final String bolt11;
+  final String bolt;
```
Comment (vincenzopalazzo) [inline lib/model/app_model/list_invoices.dart:34]:
```suggestion
  final String? bolt11;
  final String? bolt12;
```

File: lib/views/home/home_view.dart [hunk 8]
```diff
@@ -155,7 +155,11 @@ class _HomeViewState extends State<HomeView> {
             children: [
               _text(topic: "Amount", value: items[index].amount),
               _text(topic: "Description", value: items[index].description),
-              _text(topic: "Bolt11", value: items[index].bolt11),
+              _text(
+                  topic: items[index].boltIdentifier == "bolt11"
+                      ? "Bolt11"
+                      : "Bolt12",
+                  value: items[index].bolt),
```
Comment (vincenzopalazzo) [inline lib/views/home/home_view.dart:162]:
```suggestion
                  topic: items[index].topic()",
                  value: items[index].bolt),
```
Add a new function `topic` that hides the if-else logic, do not put logic inside the UI code that it is not UI specific

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]

File: lib/model/app_model/list_invoices.dart (hunk 7 above)
Comment (vincenzopalazzo) [reply lib/model/app_model/list_invoices.dart:34]: this help you keep the state if in the future you need to do somethings with it

File: lib/views/home/home_view.dart [hunk 9]
```diff
@@ -145,6 +145,20 @@ class _HomeViewState extends State<HomeView> {
...
+      return "bolt12";
+    }
+    return "bolt11";
+  }
+
+  String value(var value) {
+    if (value.bolt11 == null) {
+      return value.bolt12.toString();
+    }
+    return value.bolt11;
```
Comment (vincenzopalazzo) [inline lib/views/home/home_view.dart:159]: Very nice! I had only a comment, the parameter of a function must always have a type! otherwise the reader do not know what kind of type it is
```suggestion
  String topic(Type topic) {
    if (topic.bolt11 == null) {
      return "bolt12";
    }
    return "bolt11";
  }

  String value(Type value) {
    if (value.bolt11 == null) {
      return value.bolt12.toString();
    }
    return value.bolt11;
```

**Review by vincenzopalazzo — COMMENTED** [review]
Ok last iteration and we are ready to go

**Comment by vincenzopalazzo** [comment]
Ok now the commit needs to be squash in a more coordinated one, 9 commits are too much!

**Comment by Harshit933** [comment]
> Ok now the commit needs to be squash in a more coordinated one, 9 commits are too much!

Done!

**Review by vincenzopalazzo — APPROVED** [review]
Cool! 

Next step is putting the bolt12/11 inside a qr code with library like https://pub.dev/packages/qr_flutter

**Comment by Harshit933** [comment]
Sure
